## Assignment 1: 1D Array Operations

In [ ]:
import numpy as np

arr = np.arange(1, 11)

print("Array:", arr)

print("Shape:", arr.shape)

print("Data type:", arr.dtype)

print("Sum of elements:", arr.sum())

print("Mean of elements:", arr.mean())

print("Maximum value:", arr.max())
print("Minimum value:", arr.min())

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data type: int64
Sum of elements: 55
Mean of elements: 5.5
Maximum value: 10
Minimum value: 1


## Assignment 2: Matrix Arithmetic

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

C_add = A + B
print("\nMatrix Addition (A + B):\n", C_add)

C_sub = A - B
print("\nMatrix Subtraction (A - B):\n", C_sub)

C_elem_mul = A * B
print("\nElement-wise Multiplication (A * B):\n", C_elem_mul)

C_mat_mul = np.dot(A, B)
print("\nMatrix Multiplication (A @ B):\n", C_mat_mul)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction (A - B):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication (A * B):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication (A @ B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## Assignment 2: Matrix Arithmetic

In [ ]:
import numpy as np

marks = np.array([[85, 90, 88, 92],
                  [70, 65, 72, 68],
                  [95, 91, 93, 96],
                  [60, 75, 70, 80],
                  [88, 84, 86, 90]])

print("Student Marks:\n", marks)

avg_student_marks = np.mean(marks, axis=1)
print("\nAverage marks of each student:", avg_student_marks)

avg_subject_marks = np.mean(marks, axis=0)
print("Average marks of each subject:", avg_subject_marks)

highest_mark = np.max(marks)
lowest_mark = np.min(marks)
print("Highest mark overall:", highest_mark)
print("Lowest mark overall:", lowest_mark)

total_marks_per_student = np.sum(marks, axis=1)
highest_total_marks_student_index = np.argmax(total_marks_per_student)
print("\nTotal marks per student:", total_marks_per_student)
print(f"Student with the highest total marks (index): {highest_total_marks_student_index} (Student {highest_total_marks_student_index + 1})")
print(f"Highest total marks: {total_marks_per_student[highest_total_marks_student_index]}")

Student Marks:
 [[85 90 88 92]
 [70 65 72 68]
 [95 91 93 96]
 [60 75 70 80]
 [88 84 86 90]]

Average marks of each student: [88.75 68.75 93.75 71.25 87.  ]
Average marks of each subject: [79.6 81.  81.8 85.2]
Highest mark overall: 96
Lowest mark overall: 60

Total marks per student: [355 275 375 285 348]
Student with the highest total marks (index): 2 (Student 3)
Highest total marks: 375


## Assignment 4: Image Processing using NumPy

In [ ]:
import numpy as np

image = np.array([[100, 120, 130],
                  [150, 180, 200],
                  [ 50,  80, 100]])

print("Original Image:\n", image)

normalized_image = image / 255.0
print("\nNormalized Image:\n", normalized_image)

bright_image = image + 30
print("\nImage with Increased Brightness:\n", bright_image)

clipped_image = np.clip(bright_image, 0, 255)
print("\nClipped Image (values above 255 set to 255):\n", clipped_image)

average_intensity = np.mean(image)
print("\nAverage Pixel Intensity of Original Image:", average_intensity)

Original Image:
 [[100 120 130]
 [150 180 200]
 [ 50  80 100]]

Normalized Image:
 [[0.39215686 0.47058824 0.50980392]
 [0.58823529 0.70588235 0.78431373]
 [0.19607843 0.31372549 0.39215686]]

Image with Increased Brightness:
 [[130 150 160]
 [180 210 230]
 [ 80 110 130]]

Clipped Image (values above 255 set to 255):
 [[130 150 160]
 [180 210 230]
 [ 80 110 130]]

Average Pixel Intensity of Original Image: 123.33333333333333


## Assignment 5: Data Analysis using NumPy

In [ ]:
import numpy as np

sales = np.array([[120, 130, 140, 150, 160, 170],
                  [100, 110, 120, 130, 140, 150],
                  [150, 145, 160, 170, 180, 190],
                  [ 90, 100, 110, 120, 130, 140]])

print("Monthly Sales Data:\n", sales)

total_sales_per_product = np.sum(sales, axis=1)
print("\nTotal sales of each product:", total_sales_per_product)

avg_monthly_sales_per_product = np.mean(sales, axis=1)
print("Average monthly sales of each product:", avg_monthly_sales_per_product)

best_selling_product_index = np.argmax(total_sales_per_product)
print(f"Best-selling product (index): {best_selling_product_index} (Product {best_selling_product_index + 1})")
print(f"Highest total sales: {total_sales_per_product[best_selling_product_index]}")

total_sales_per_month = np.sum(sales, axis=0)
highest_sales_month_index = np.argmax(total_sales_per_month)
print("\nTotal sales per month:", total_sales_per_month)
print(f"Month with the highest overall sales (index): {highest_sales_month_index} (Month {highest_sales_month_index + 1})")
print(f"Highest overall sales for a month: {total_sales_per_month[highest_sales_month_index]}")

std_dev_sales_per_product = np.std(sales, axis=1)
print("\nStandard deviation of sales for each product:", std_dev_sales_per_product)

Monthly Sales Data:
 [[120 130 140 150 160 170]
 [100 110 120 130 140 150]
 [150 145 160 170 180 190]
 [ 90 100 110 120 130 140]]

Total sales of each product: [870 750 995 690]
Average monthly sales of each product: [145.         125.         165.83333333 115.        ]
Best-selling product (index): 2 (Product 3)
Highest total sales: 995

Total sales per month: [460 485 530 570 610 650]
Month with the highest overall sales (index): 5 (Month 6)
Highest overall sales for a month: 650

Standard deviation of sales for each product: [17.07825128 17.07825128 15.92081098 17.07825128]
